go-lang-plugin-org/go-lang-idea-plugin

src/com/goide/psi/impl/imports/GoImportReferenceHelper.java, src/com/goide/sdk/GoSdkType.java, src/com/goide/sdk/GoSdkUtil.java, tests/com/goide/GoCodeInsightFixtureTestCase.java, tests/com/goide/sdk/GoSdkUtilTest.java
In version **1.4** the format of the `zversion.go` file has been changed that broke the SDK version detection logic. Besides all SDK src files were moved from `${GOROOT}/src/pkg` to `${GOROOT}/src`. This pull request makes the plugin aware of those changes.
=> Add support for go1.4 SDK

resources/liveTemplates/go.xml
-quick fix on replacing null with nil in the go.xml template
great work thanks for all the effort, the alpha branch is great.
Signed-off-by: Brent Salisbury <brent@socketplane.io>
=> replaced /null/nil/ in the go livetemplate

jps-plugin/src/com/goide/jps/model/JpsGoSdkType.java, src/META-INF/plugin.xml, src/com/goide/actions/fmt/GoImportsFileAction.java
Hello,
goimports is now in code menu. 
It assumes that goimports is already installed. A shortcut is missing. I tested goimports on macos 10.10.2 with go 1.4.1 and intellij 14.0.3.
=> Added goimports to code menu. 

jps-plugin/tests/com/goide/jps/GoBuilderTest.java, src/com/goide/sdk/GoSdkType.java
This allows me to have the Browse for sdk folder dialog open directly in the SDK dir.
I've followed the instructions from here: [http://golang.org/doc/install#tarball](http://golang.org/doc/install#tarball)
Also, the tests now finally pass on my computer due to this.
=> Improve default path detection for go SDK

src/com/goide/editor/GoParameterInfoHandler.java, testData/parameterInfo/funcEmbedInner.go, testData/parameterInfo/funcEmbedOuter.go, testData/parameterInfo/funcParam.go, testData/parameterInfo/funcParamEllipsis.go, testData/parameterInfo/funcParamMulti.go, testData/parameterInfo/funcParamNone.go, testData/parameterInfo/methParam.go, testData/parameterInfo/methParamEllipsis.go, testData/parameterInfo/methParamNone.go, tests/com/goide/editor/GoParameterInfoHandlerTest.java
The parameter info help has not worked correctly in cases when parameters where declared like this `a, b, c int` or this `more ...int`. Those cases were fixed and a test case suite was added to confirm that.
=> [1.0] Fix parameter info help (fixes #1214)

src/com/goide/actions/fmt/GoImportsFileAction.java
Running the goimports tool was failing on Windows because it searches for "goimports" and not "goimports.exe."
=> Fix running goimports when on Windows.

utils/src/com/goide/GoEnvironmentUtil.java
With these changes I can now set the Go AppEngine SDK again.
There's a TODO which should be looked at before doing the merge. If agreed I can simply remove the commented line but I want to have some input first.
Thank you.
=> Improved support for AppEngine SDK (fixes #1278)

src/com/goide/GoAnnotator.java, src/com/goide/highlighting/GoColorsAndFontsPage.java, src/com/goide/highlighting/GoSyntaxHighlightingColors.java
This adds support for different highlight options per level and type as described in #1241
=> Add highlight support for different visibility levels per type (fixes #1241, #1257, #1319)

src/com/goide/runconfig/before/GoBeforeRunTaskProvider.java
I can't compile the plugin on the latest branch without this change :)
=> Fix compilation for not-JetBrains environments

src/com/goide/sdk/GoSdkUtil.java
With this I can create AppEngine SDKs again.
While debugging this I've noticed two things:
- an SDK can't be created if the version returned is unknown
- the tests don't cover AppEngine and how the comparison should take effect for versions
=> Detection of AppEngine SDK versions

src/com/goide/GoDocumentationProvider.java, testData/mockSdk-1.1.2/src/pkg/docs/docs.go, tests/com/goide/GoDocumentationProviderTest.java
This works only if the documentation is present at the moment.
=> Show func and method signature in quick doc (fixes #1234)

src/com/goide/psi/impl/GoPsiImplUtil.java, testData/parameterInfo/fieldMethCall.go, tests/com/goide/editor/GoParameterInfoHandlerTest.java
Parameter help is not provided for calls that are made on struct fields, e.g. `a.b.f(1, "foo")`. This PR fixes this deficiency.
=> Parameters help does not work for method calls made on struct fields

src/com/goide/sdk/GoSdkUtil.java, tests/com/goide/sdk/GoSdkUtilTest.java
This should prevent future developments of the go devel version changes to stop the plugin recognizing it.
=> Better regex matcher for Go tip (fix #1279)

resources/inspectionDescriptions/GoReservedWordUsedAsName.html, src/META-INF/plugin.xml, src/com/goide/inspections/GoRenameQuickFix.java, src/com/goide/inspections/GoReservedWordUsedAsName.java, testData/highlighting/ranges.go, testData/highlighting/struct.go, tests/com/goide/inspections/GoHighlightingTest.java
Lets see if I've understood anything from today :D 
I'm not really sure about the 
```java
String functionName = psiElement.getText();
for (GoFunctionDeclaration builtinFunctionDeclaration : builtin.getFunctions()) {
if (builtinFunctionDeclaration.getIdentifier().getText().equals(functionName)) {
```
part but I don't see another way to get the identifier text out of it.
Also, I'm sorry for the commit noise related to the white space at the end of the lines.
One last thing that's not clear to me is why all the tests that break now break because of the missing description which wasn't there in the first place. On master everything works as expected, on this branch once I have errors/warnings from the inspections, tests break.
Thank you!
=> Add inspection for functions with the same name as builtin functions (fixes #1450)

src/com/goide/runconfig/GoBuildingRunner.java, src/com/goide/runconfig/application/GoApplicationRunningState.java, src/com/goide/runconfig/ui/GoApplicationConfigurationEditorForm.form, src/com/goide/runconfig/ui/GoApplicationConfigurationEditorForm.java
The only thing that I'd change to this is to make the output file dialog open to either the project root or to GOPATH/bin by default (but I don't know how to do this yet) and it can still be used as is.
=> Go Build: output file customisation (fixes #1658)

src/com/goide/inspections/GoInspectionUtil.java, tests/com/goide/inspections/GoInspectionUtilTest.java
Due to `GoBuiltinCallExpr` is used for `make` and `new` calls only, I think it's safe to say that it returns a single value.
See GoParserUtil:
https://github.com/eugene-auduchinok/go-lang-idea-plugin/blob/497fcd84047d91cb8907f1585e8d298074c1f976/src/com/goide/parser/GoParserUtil.java#L167-167
=> Fix result count for 'make', 'new' functions (fixes #1760)

src/com/goide/psi/impl/GoNamedElementImpl.java, tests/com/goide/psi/impl/GoNamedElementTest.java
Is it efficient to get use scopes this way?
=> Proper getUseScope for local variables and constants

src/com/goide/inspections/GoAssignmentNilWithoutExplicitType.java, testData/highlighting/nil.go, testData/highlighting/simple.go, tests/com/goide/inspections/GoHighlightingTest.java
There was an inspection for nil assignments to variables but it hadn't work for short assignments or constants, so I've fixed it.
=> Fix nil assignment inspection for short vars, constants declarations 

tests/com/goide/completion/GoCompletionSdkAwareTest.java, tests/com/goide/completion/GoCompletionSdkAwareTestBase.java, tests/com/goide/completion/GoExcludedPackagesTest.java
After previous tests cleanup we had tests in `GoCompletionSdkAwareTest` run twice because of inheritance.
=> Fix tests inheritance

src/com/goide/psi/GoFile.java, src/com/goide/util/GoUtil.java, tests/com/goide/inspections/GoHighlightingTest.java, tests/com/goide/util/GoUtilTest.java
This patch modifies GoUtil.getAllPackagesInDirectory to test for build tags
when evaluating whether a file should be scanned for packages.
This also modifies GoFile.hasCPathImport to simply look for 'import "C"'
rather than getImportMap. This avoids an infinite recursion
(getImportMap depends on getAllPackagesInDirectory).
This fixes the bug identified in
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1858
Read on for a brief description of the bug:
In the Go source distribution, you have situations like
src/runtime/mkduff.go -> package main, // build +ignore
src/runtime/trace.go -> package runtime, no build tag
src/strconv/makeisprint.go -> package main, // build +ignore
src/strconv/itoa.go -> package strconv, no build tag
In your program, you do
import "runtime"
import …
=> fix spurious "redeclared import" warnings

CONTRIBUTING.md
As I've talked with @ignatov on Gitter, I've understood that's now mandatory to have a signed CLA for people to contribute to the plugin. As such, we should reflect this into the documentation we provide.
It also fixes #1856 and has some other small tweaks.
=> Added CLA information and small tweaks to the contributing document

CONTRIBUTING.md
Update the project setup instructions, so that contributors know to replace the .idea configuration that IDEA Gradle import blows away.
=> change project setup instructions to keep .idea config.

gen/com/goide/parser/GoParser.java, gen/com/goide/psi/GoTag.java, gen/com/goide/psi/impl/GoTagImpl.java, grammars/go.bnf, resources/META-INF/plugin.xml, resources/inspectionDescriptions/GoStructTag.html, src/com/goide/inspections/GoStructTagInspection.java, testData/highlighting/structTags.go, testData/parser/Simple.txt, tests/com/goide/inspections/GoHighlightingTest.java
This is an incomplete implementation of
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1983. It will
raise warnings if it detects a tag value that does not conform to the Go
StructTag convention described by https://golang.org/pkg/reflect/#StructTag.
Currently, the inspector does not validate that the tag value strings are valid
and is therefore overly permissive.
Its implementation is essentially ported from validateStructTag in
https://github.com/golang/tools/blob/master/cmd/vet/structtag.go.
=> add an inspection for StructTag

src/com/goide/inspections/GoContinueNotInLoopInspection.java, src/com/goide/psi/impl/GoElementFactory.java, testData/quickfixes/continue-outside-loop/simple-after.go, testData/quickfixes/continue-outside-loop/simple.go, tests/com/goide/quickfix/GoContinueNotInLoopQuickFixTest.java
This change adds a 'replace with return' quick fix and addresses
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2002.
Not sure if this is a worthwhile quickfix (not hard to just type 'return')...
=> Add 'replace with return' quick fix

src/com/goide/dlv/DlvDebugProcess.java
Go won't store the target path of the symlink, so for example if the file is in `/home/florin/golang/src/github.com/dlsniper/u/demo/dbg/demo1/demo1.go` and the project is under `/home/florin/demo1` which points to `/home/florin/golang/src/github.com/dlsniper/u/demo/dbg/demo1` then when building `/home/florin/demo1` then the Go compiler will store the `/home/florin/demo1/demo1.go` not `/home/florin/golang/src/github.com/dlsniper/u/demo/dbg/demo1/demo1.go`. I'm sorry I can't explain it better, but this PR fixes the issue described in #1880 (I've tested locally for it). Thank you.
=> Use symlinked path for breakpoints (fix #1880)

src/com/goide/inspections/GoContinueNotInLoopInspection.java, testData/highlighting/continue.go
Previously the inspector would look for the presence of a GoForStatement
parent of a continue statement. This did not take into account the
presence of 'go' or 'defer' calls, e.g.
```go
for {
defer func() {
continue // no error was raised, should be an error
}()
}
```
The discussion at
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2024
reminded me that the continue inspection suffers from this problem.
=> fix 'continue not in a loop' inspector

resources/META-INF/plugin.xml, resources/inspectionDescriptions/GoDeferInLoop.html, src/com/goide/inspections/GoDeferInLoop.java, testData/highlighting/deferInLoop.go, tests/com/goide/inspections/GoHighlightingTest.java
This adds the inspection that checks if a defer is called inside a for loop (which could potentially cause a resource leak).
=> Add inspection for using defer in a for loop (fixes #1776)

src/com/goide/highlighting/GoHighlightExitPointsHandlerFactory.java, tests/com/goide/editor/GoExitPointsHighlightingTest.java
If cursor is on func keyword highlight all the exit points of this function (return and panic statements)
I don't know if this feature is really needed, it is up to you whether to accept this PR.
However, such highlighting is supported in Scala plugin for IDEA, and I find it to be really useful.
=> Highlight exit points of a function when cursor is on `func`

src/com/goide/runconfig/testing/GoTestRunningState.java
I've tested this using `-race` both on and off and things still look ok.
=> Use covermode atomic for tests coverage (fixes #2037)

src/com/goide/codeInsight/imports/GoGetPackageFix.java
As a start for fixing https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2053, this allows for running `go get` for test packages and sub-packages as well.
=> Run go get for test packages and sub-packages

src/com/goide/GoDocumentationProvider.java, testData/doc/constants.go, testData/doc/constants.txt, tests/com/goide/GoDocumentationProviderTest.java
If a GoReferenceExpression is a reference to a const, an annotation will be
created with the text of the constant's definition.
Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1422.
=> add definition annotation for const ref

src/com/goide/inspections/GoVarDeclarationInspection.java, testData/highlighting/assignUsages.go
Previously the plugin would not complain when doing something like
```go
x := 1, 2
```
whereas
```go
var x int = 1, 2
```
would produce the correct error.
=> extend assignment count check to short var decl

src/com/goide/highlighting/GoAnnotator.java, testData/highlighting/ranges.go, testData/highlighting/simple.go
Checks the following scenario:
```go
func foo() {
string     // error: Type string is not an expression.
}
```
Partially addresses https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1588.
=> Add an annotator check for type ref used as expr

src/com/goide/sdk/GoSdkUtil.java, src/com/goide/sdk/GoSmallIDEsSdkService.java, utils/src/com/goide/GoConstants.java
As reported by @stuartcarnie on Gitter, Go 1.6 has moved `zversion.go`; now found in `runtime/internal/sys/zversion.go`
This PR addresses that.
May I also suggest releasing the plugin on all channels (nightly, alpha and stable) with this change? I know from previous experience about the number of tickets that the old plugin didn't supported Go 1.4 (or was it 1.5?) when that appeared and changed the way this works.
=> Go 1.6 SDK detection

src/com/goide/inspections/GoDuplicateFieldsOrMethodsInspection.java, testData/highlighting/githubIssue2099.go, tests/com/goide/inspections/GoHighlightingTest.java
Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2099.
This should be considered a short-term fix until general embedded type support is implemented.
=> Ignore embedded types when finding duplicate methods

src/com/goide/psi/impl/GoCompositeElementImpl.java, testData/highlighting/typeConversion.go, tests/com/goide/inspections/GoHighlightingTest.java
Previously, the plugin did not consider a case statement to be a separate scope
for reference resolution purposes.
Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2139.
=> Fix decls in case clause "leaking" to next clauses

src/com/goide/runconfig/testing/GoTestRunningState.java
Technically only directory run configs have this issue (package running doesn't support specifying `...` yet, I'll do a different PR for that if it's deemed of interested, so far no such request tho).
=> Improve coverage support for packages (fixes #2276)

resources/META-INF/plugin.xml, src/com/goide/runconfig/testing/GoTestFinder.java, src/com/goide/runconfig/testing/GoTestFramework.java, src/com/goide/runconfig/testing/GoTestRunConfigurationProducerBase.java, src/com/goide/runconfig/testing/GoTestRunningState.java, src/com/goide/runconfig/testing/frameworks/gobench/GobenchEventsConverter.java, src/com/goide/runconfig/testing/frameworks/gobench/GobenchFramework.java, src/com/goide/runconfig/testing/frameworks/gobench/GobenchRunConfigurationProducer.java, src/com/goide/runconfig/testing/frameworks/gobench/GobenchRunningState.java, src/com/goide/runconfig/testing/frameworks/gocheck/GocheckRunConfigurationProducer.java, src/com/goide/runconfig/testing/frameworks/gotest/GotestRunConfigurationProducer.java, src/com/goide/runconfig/testing/ui/GoTestRunConfigurationEditorForm.form, src/com/goide/runconfig/testing/ui/GoTestRunConfigurationEditorForm.java
Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1995.
Please take a look at the event converter class. It's not complete but I don't want to keep working on it if there's an easier way. The main reason I can't use `processServiceMessage` is that the go test -bench output is not line-delimited.
=> add go bench framework

src/com/goide/highlighting/GoColorsAndFontsPage.java, src/com/goide/highlighting/GoHighlightingAnnotator.java, src/com/goide/highlighting/GoSyntaxHighlightingColors.java, testData/colorHighlighting/builtinFunctions.go, testData/colorHighlighting/funcAndMethod.go, testData/colorHighlighting/label.go, testData/colorHighlighting/octAndHex.go, testData/colorHighlighting/simple.go, testData/colorHighlighting/types.go, tests/com/goide/editor/GoHighlightingAnnotatorTest.java
This introduces support for highlighting builtin functions. However to do this, the test class had to be updated which lead to the noise in the PR.
=> Introduce support for builtin function highlighting (fixes #1841)

ISSUE_TEMPLATE.md
As Github finally added this feature, we should make use of it.
This is the announcement blog post: https://github.com/blog/2111-issue-and-pull-request-templates
Please let me know if we should add anything missing to it.
Thank you.
P.S. Should I also add a PR template to ask if people have a signed CLA?
=> Add support for Github issue template

src/com/goide/completion/GoKeywordCompletionContributor.java, src/com/goide/completion/GoReferenceCompletionProvider.java, src/com/goide/completion/GoStructLiteralCompletion.java, src/com/goide/psi/impl/GoFieldNameReference.java, src/com/goide/psi/impl/GoPsiImplUtil.java, tests/com/goide/completion/GoCompletionTest.java
Do not suggest field names when value initializer is used.
Do not suggest values when field:value initializer is used.
Only show unassigned fields in completion list.
=> Improve completion in struct literals

resources/META-INF/plugin.xml, resources/colorscheme/Darcula - dlsniper.xml
I'd like to add the theme that I'm using daily since about a year now, see below. I've spoke briefly about this on Gitter, so hope it's ok.
There are some people that agree we could ship better default themes but I'm not sure how to achieve that right now.
I've looked at a few themes on http://color-themes.com/ (lovely website btw) and I have a few suggestions to add:
- white backgrounds:
- [Relax Your Eyes](http://color-themes.com/?view=theme&id=563a1a6e80b4acf11273ae76)
- [Classic Eclipse](http://color-themes.com/?view=theme&id=563a1a6b80b4acf11273ae67)
- [Codding Horror](http://color-themes.com/?view=theme&id=563a1a6a80b4acf11273ae63)
- dark backgrounds:
- [Monokai Sublime Text 3](http://color-themes.com/?view=theme&id=563a1a7680b4acf11273ae94) *
- [Base16 …
=> Added custom theme

src/com/goide/psi/impl/GoStubbedElementImpl.java
Somehow this `toString` can end up being called by Swing when trying to do GoTo symbol: [stacktrace]
[stacktrace]: https://gist.github.com/matklad/95835f52a50e1e3b9bab0936e925a76e
=> Don't load AST in toString

resources/META-INF/plugin.xml, resources/inspectionDescriptions/GoUnusedExportedFunction.html, resources/inspectionDescriptions/GoUnusedFunction.html, src/com/goide/inspections/unresolved/GoUnusedExportedFunctionInspection.java, src/com/goide/inspections/unresolved/GoUnusedFunctionInspection.java, tests/com/goide/inspections/GoHighlightingTest.java
Following the chat here: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2515#issuecomment-218720494 this splits the unused function inspection
=> Split unused function inspection (fixes #2374)

src/com/goide/inspections/GoImportUsedAsNameInspection.java, src/com/goide/inspections/GoRedeclareImportAsFunctionInspection.java, testData/highlighting/importUsedAsName.go
The inspections should probably be unified? Or it's better to keep them separate so that they can be disabled independently?
=> Fix underscore used as name inspections (#fixes 2716)

src/com/goide/GoParserDefinition.java
Fix `KEYWORDS` attribute(`TokenSet` type) in `GoParserDefinition.java` file has 27 keywords which have two repeating keywords `PACKAGE` and `IMPORT`.
=> Fix keywords repeated(#fixes 2733)

README.md, pluginResources/META-INF/plugin.xml
it was announed on Nov 2, 2017: https://blog.jetbrains.com/go/2017/11/02/announcing-goland-former-gogland-eap-18-final-product-name-templates-support-and-more
=> fix name of the IDE: Gogland > GoLand
