CONTRIBUTING.md

Updated contributing file

---

src/com/goide/psi/impl/GoPsiImplUtil.java
testData/psi/importDeclaration/addImportBeforeFunction_after.go
testData/psi/importDeclaration/addImportToListWithMultiSpecDeclaration_after.go
testData/psi/importDeclaration/addImportToListWithSingleSpecDeclarationWithParens_after.go
testData/psi/importDeclaration/addImportToListWithSingleSpecDeclaration_after.go

Add newline after inserted import in group

---

src/com/goide/project/GoProjectLibrariesService.java

Support for file-based projects (.ipr)

Update GoProjectLibrariesService.java (fixes #1340)

---

src/META-INF/plugin.xml
src/com/goide/ui/ProjectTutorialNotification.java
src/com/goide/util/GoUtil.java
utils/src/com/goide/GoConstants.java

This is the refactoring of #1357

Add a usage notification

---

.travis.yml
fetchIdea.sh
travis.sh

According to [the docs](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) it should be faster to build like this.

Use container instances for TravisCI

---

.travis.yml
fetchIdea.sh
travis.sh

Reverts go-lang-plugin-org/go-lang-idea-plugin#1404

Revert "Use container instances for TravisCI"

---

src/com/goide/editor/GoFoldingBuilder.java
testData/folding/simple.go

Add code folding for function literals.

---

CONTRIBUTING.md
README.md

Hopefully this will be useful to some.

Introduce FAQ

---

src/com/goide/actions/fmt/GoImportsFileAction.java

I guess this one was missed in a refactoring but things work now properly :)

Add missing -w parameter to goimports (fixes #1538)

---

src/com/goide/editor/GoFoldingBuilder.java
testData/folding/simple.go

I'm not sure if the test quality is good enough but it seems it's passing and testing it in real world works as well.

Don't fold empty types (fixes #1549)

---

resources/inspectionDescriptions/GoDuplicateMethod.html
src/META-INF/plugin.xml
src/com/goide/inspections/GoDuplicateMethodInspection.java
tests/com/goide/inspections/GoHighlightingTest.java

Simple implementation
relates issue(s): #1023

Duplicate method inspection

---

src/com/goide/appengine/run/GoAppEngineRunningState.java
src/com/goide/runconfig/GoBuildingRunner.java
src/com/goide/runconfig/GoRunConfigurationBase.java
src/com/goide/runconfig/application/GoApplicationRunningState.java
src/com/goide/runconfig/file/GoRunFileRunningState.java
src/com/goide/runconfig/testing/GoTestRunningState.java
src/com/goide/runconfig/ui/GoCommonSettingsPanel.form
src/com/goide/runconfig/ui/GoCommonSettingsPanel.java
src/com/goide/util/GoExecutor.java

There's one thing that this doesn't do properly right now, sent the ```Program arguments``` to the actual executable, I'm still working on that on, should be here soon.

Introduce different parameter list for go tool and the user app

---

src/com/goide/util/GoBuildMatcher.java
src/com/goide/util/GoUtil.java
tests/com/goide/util/GoBuildMatcherTest.java

fixes #1199
Also currently two files in same directory (gen1, get2 for example)
```go
// +build ignore
package main;
func test() {
}
```
produce test function is duplicates

Process +build flags (fixes #1199)

---

src/com/goide/GoAnnotator.java
src/com/goide/highlighting/GoColorsAndFontsPage.java
src/com/goide/highlighting/GoSyntaxHighlightingColors.java
testData/colorHighlighting/label.go
tests/com/goide/editor/GoHighlightingAnnotatorTest.java

Make label highlighting configurable

---

src/com/goide/actions/GoCreateFileAction.java
src/com/goide/psi/impl/GoPsiImplUtil.java
testData/actions/createFile/a.go
tests/com/goide/actions/GoCreateFileActionTest.java
tests/com/goide/psi/impl/GoPsiImplUtilTest.java

I've fixed some things, added tests and rebased.

Use proper package name when create file

---

resources/inspectionDescriptions/GoTestSignatures.html
src/META-INF/plugin.xml
src/com/goide/inspections/GoTestSignaturesInspection.java
src/com/goide/inspections/unresolved/GoUnusedFunctionInspection.java
src/com/goide/psi/impl/GoElementFactory.java
src/com/goide/runconfig/testing/GoTestFinder.java
src/com/goide/runconfig/testing/GoTestFunctionType.java
src/com/goide/runconfig/testing/GoTestRunConfigurationProducerBase.java
testData/inspections/test-signatures/benchmark_test-after.go
testData/inspections/test-signatures/benchmark_test.go
testData/inspections/test-signatures/exampleNonEmptySignature_test-after.go
testData/inspections/test-signatures/exampleNonEmptySignature_test.go
testData/inspections/test-signatures/testLocalTestingImport_test-after.go
testData/inspections/test-signatures/testLocalTestingImport_test.go
testData/inspections/test-signatures/testMain_test-after.go
testData/inspections/test-signatures/testMain_test.go
testData/inspections/test-signatures/testNoTestingImport_test-after.go
testData/inspections/test-signatures/testNoTestingImport_test.go
testData/inspections/test-signatures/testWrongTestingAlias_test-after.go
testData/inspections/test-signatures/testWrongTestingAlias_test.go
testData/mockSdk-1.1.2/src/pkg/testing/testing.go
tests/com/goide/inspections/GoHighlightingTest.java
tests/com/goide/inspections/GoTestSignaturesInspectionTest.java
utils/src/com/goide/GoConstants.java

All testing functions (Test/Benchmark/Example) in test files should have appropriate signature (http://golang.org/pkg/testing/) and the first symbol after testing prefix must not be a lowercase letter.
I've created anonymous inner classes for quick fixes but I'm not sure if it had been better to create separated named classes.
Would it be better if I combine quick fixes into a single class? Or would it be better if I split inspection otherwise?
I haven't created tests yet as I'm not sure if I've done all these things right.

Add GoTestingDeclarationsInspection

---

resources/inspectionDescriptions/GoAssignmentNilWithoutExplicitType.html
src/META-INF/plugin.xml
src/com/goide/inspections/GoAssignmentNilWithoutExplicitType.java
src/com/goide/runconfig/GoRunConfigurationWithMain.java
src/com/goide/runconfig/testing/GoTestRunConfiguration.java
tests/com/goide/inspections/GoHighlightingTest.java

Fix for this error https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1515

Use relative path with working directory (fixes # 1515)

---

src/com/goide/inspections/GoInspectionUtil.java
testData/highlighting/mismatch.go

Add void assignment case in GoVarDeclarationInspection

---

src/com/goide/inspections/unresolved/GoIntroduceLocalVariableFix.java
src/com/goide/refactor/GoIntroduceVariableBase.java
src/com/goide/refactor/GoRefactoringUtil.java
testData/quickfixes/local-variable/resolved-after.go
testData/quickfixes/local-variable/resolved.go
testData/quickfixes/local-variable/unresolved-after.go
testData/quickfixes/local-variable/unresolved.go
tests/com/goide/quickfix/GoCreateLocalVariableQuickFixTest.java
tests/com/goide/quickfix/GoQuickFixTestBase.java

Proper local variable introduce fix, checks for other occurrences of the reference.

Reuse occurrences and anchor search in GoIntroduceLocalVariableFix

---

src/com/goide/inspections/GoNoNewVariablesInspection.java
testData/highlighting/shortVars.go

Fix no new variable inspection for shadowing in 'for clause' case

---

src/com/goide/psi/impl/GoPsiImplUtil.java
testData/highlighting/shortVars.go

A fix for wrong variable resolve in for clause. I hope it didn't break anything not covered with tests.
Fixes #1752.

ForClause var shadowing resolve fix

---

src/com/goide/codeInsight/imports/GoImportPackageQuickFix.java
src/com/goide/completion/GoAutoImportCompletionContributor.java
src/com/goide/completion/GoImportPathsCompletionProvider.java
src/com/goide/psi/GoFile.java
src/com/goide/runconfig/testing/GoTestFinder.java
src/com/goide/util/GoUtil.java
tests/com/goide/codeInsight/imports/GoReferenceImporterTest.java
tests/com/goide/completion/GoCompletionSdkAwareTest.java
tests/com/goide/completion/GoCompletionTest.java

Allow to import own path from test file

---

src/com/goide/runconfig/testing/frameworks/gotest/GotestEventsConverter.java
testData/testing/gotest/singleTestLeadingSpaceOk-expected.txt
testData/testing/gotest/singleTestLeadingSpaceOk.txt
tests/com/goide/runconfig/testing/GotestEventsConverterTest.java

Addresses https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1853

fix leading spaces causing failure to match test name

---

src/com/goide/inspections/GoUnusedImportDeclaration.java
src/com/goide/psi/GoFile.java
testData/highlighting/doNotReportNonLastMultiResolvedImport.go
testData/highlighting/relativeImportIgnoringDirectories.go
tests/com/goide/inspections/GoHighlightingTest.java

Addresses https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1461

consider aliases and path names when looking for dupe imports

---

src/com/goide/inspections/GoUnusedImportDeclaration.java
tests/com/goide/inspections/GoHighlightingTest.java

Addresses https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1866.

Don't look at '_' or '.' imports while looking for redeclarations

---

resources/META-INF/plugin.xml

Since users will also look into this.

Clarify supported builds

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/GoContinueNotInLoop.html
src/com/goide/inspections/GoContinueNotInLoopInspection.java
testData/highlighting/continue.go
tests/com/goide/inspections/GoHighlightingTest.java

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2002.

add an inspection for 'continue' outside loop

---

build.gradle
testData/performance/GoUnusedFunction/expected.xml
testData/performance/GoUnusedImport/expected.xml

As Docker 1.5 is deprecated and soon docker hub will stop working with 1.5 version, I think this version should be updated. Please see the following link for details: https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/
Hope it helps.

Update docker to the latest version

---

src/com/goide/highlighting/GoAnnotator.java
testData/highlighting/simple.go

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1420.

Add check for package used without selector

---

src/com/goide/highlighting/GoAnnotator.java
testData/highlighting/simple.go

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2079.

add check for missing key in map literal

---

src/com/goide/inspections/GoFunctionCallInspection.java
testData/highlighting/simple.go

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/497.

add check to ensure that type conversion has 1 arg

---

src/com/goide/highlighting/GoAnnotator.java
testData/highlighting/declaredButNotUsed.go
testData/highlighting/labels.go
testData/highlighting/returns.go
testData/highlighting/simple.go
tests/com/goide/inspections/GoHighlightingTest.java

Reverts go-lang-plugin-org/go-lang-idea-plugin#2128

Revert "Introduce declared but not used inspection for literals (fixes #1310)"

---

src/com/goide/highlighting/GoAnnotator.java
testData/highlighting/builtinFuncCalls.go

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2132.

Fix builtin make integer type check

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/GoPlaceholderCount.html
src/com/goide/inspections/GoPlaceholderCountInspection.java
testData/highlighting/placeholderCount.go
testData/mockSdk-1.1.2/src/pkg/log/log.go
tests/com/goide/inspections/GoHighlightingTest.java

This introduces the inspection to check the placeholders numbers vs number of arguments for functions like Printf or Sprintf

Introduce inspection for placeholders (fixes #1392)

---

src/com/goide/highlighting/GoAnnotator.java
src/com/goide/psi/impl/GoCType.java
src/com/goide/psi/impl/GoLightType.java
src/com/goide/psi/impl/GoPsiImplUtil.java
src/com/goide/psi/impl/GoReference.java
testData/highlighting/builtinFuncCalls.go

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2140.

Whitelist C types from make args typecheck

---

resources/META-INF/plugin.xml
src/com/goide/inspections/GoCgoInTestInspection.java
src/com/goide/inspections/GoDeferInLoopInspection.java
src/com/goide/inspections/GoFunctionVariadicParameterInspection.java
src/com/goide/inspections/GoMultiplePackagesInspection.java
src/com/goide/inspections/GoRedeclareImportAsFunctionInspection.java
src/com/goide/inspections/GoReservedWordUsedAsNameInspection.java
src/com/goide/inspections/unresolved/GoUnusedFunctionInspection.java
src/com/goide/inspections/unresolved/GoUnusedVariableInspection.java
src/com/goide/quickfix/GoDeleteQuickFix.java
src/com/goide/quickfix/GoMultiplePackagesQuickFix.java
src/com/goide/quickfix/GoRenameQuickFix.java
src/com/goide/quickfix/GoRenameToBlankQuickFix.java
tests/com/goide/inspections/GoHighlightingTest.java
tests/com/goide/quickfix/GoMultiplePackagesQuickFixTest.java
tests/com/goide/quickfix/GoRenameFunctionQuickFixTest.java
tests/com/goide/quickfix/GoRenameVarQuickFixTest.java

I've wanted to cleanup a bit the inspections / quick fixes. If you can think of anything else to go into the PR, please let me know. Thank you.

Unify and cleanup inspections / quickfixes

---

src/com/goide/highlighting/GoAnnotator.java
testData/highlighting/builtinFuncCalls.go

Fixes https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2235.

Add check for builtin.cap() parameter.

---

src/com/goide/inspections/GoPlaceholderCountInspection.java
testData/highlighting/placeholderCount.go

Improve the placeholder count inspection

---

gradle.properties
src/com/goide/dlv/DlvDebugProcess.java

I've quickly tested if the debugger still works and it appears all is good but I don't know the implications of returning null vs an actual promise there so please confirm before merging. Thank you.

Compatibility with EAP 144.3891

---

src/com/goide/ui/ProjectTutorialNotification.java
src/com/goide/util/GoUtil.java

I'm thinking we could have this done one time only and maybe use a different key / value if we want to display this again.

Improve notification display (fixes #2441)

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/GoEmptyDeclaration.html
src/com/goide/inspections/GoEmptyDeclarationInspection.java
testData/inspections/go-empty-declaration/constVoidDeclaration-after.go
testData/inspections/go-empty-declaration/constVoidDeclaration.go
testData/inspections/go-empty-declaration/importVoidDeclarationWithUpperComment.go
testData/inspections/go-empty-declaration/notVoidImportDeclaration.go
testData/inspections/go-empty-declaration/twoVoidImportsWithOneComment-after.go
testData/inspections/go-empty-declaration/twoVoidImportsWithOneComment.go
testData/inspections/go-empty-declaration/typeVoidDeclaration-after.go
testData/inspections/go-empty-declaration/typeVoidDeclaration.go
testData/inspections/go-empty-declaration/varVoidDeclarationInFunction.go
testData/inspections/go-empty-declaration/varVoidDeclarationNotInFunction-after.go
testData/inspections/go-empty-declaration/varVoidDeclarationNotInFunction.go
testData/inspections/go-empty-declaration/varVoidDeclarationWithInnerComment.go
tests/com/goide/inspections/GoEmptyDeclarationInspectionTest.java

New request instead of old closed request

Add empty declaration inspection with tests

---

testData/highlighting/gh2147.go
testData/mockSdk-1.1.2/src/pkg/sync/mutex.go
testData/mockSdk-1.1.2/src/pkg/sync/rwmutex.go
tests/com/goide/inspections/GoHighlightingTest.java

As discussed in the issue, there should be some tests to cover it.

Add tests for #2147

---

CONTRIBUTING.md

updated link to gitter svg
